### ISSUE TITLE
小仙女奶量无法统计

### ISSUE THREAD

**Issue by Mion354D** [Menci/FFXIV_ACT_Plugin_ZH#1]
小仙女的奶, 来源显示unknown, 奶量会被统计到被奶的人的HPS里

**Comment by Mion354D** [comment]
也有同样问题

**Comment by T-DevilW** [comment]
我检查了一下，原版插件在国服会把小仙女的群HOT算进Unknown，适配版插件甚至会把庇护所、野战治疗阵、深谋远虑、异想的融光和告解全部算进Unknown

**Comment by Menci** [comment]
原因大概是因为我把技能信息的 xml 改错了，插件 parse 失败，关于技能效果的包括治疗、持续伤害都是有问题的

**Comment by Menci** [comment]
fixed
